# Generated by Django 5.0.8 on 2024-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
