# Generated by Django 5.0.7 on 2024-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
