# Generated by Django 5.0.8 on 2024-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_merchant_id_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
