# Generated by Django 5.0.8 on 2024-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
