# Generated by Django 5.1 on 2024-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
